### ISSUE TITLE
Calling lazy() on a filename that doesn't exist produces confusing error

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/uproot4#120]
This is what happens if you call `lazy()` on a path that doesn't exist:

```python
>>> import uproot4
>>> uproot4.lazy('nonexistent_file.root')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mproffit/miniconda3/lib/python3.8/site-packages/uproot4/behaviors/TBranch.py", line 585, in lazy
    raise ValueError(
ValueError: allow_missing=True and no TTrees found in

    
```

Obviously this doesn't really indicate the actual problem--that the file doesn't exist. It also strangely claims that `allow_missing=True`, which is not correct since the default is `False`. It says the same thing even if you explicitly set `allow_missing=False`:

```python
>>> uproot4.lazy('nonexistent_file.root', allow_missing=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mproffit/miniconda3/lib/python3.8/site-packages/uproot4/behaviors/TBranch.py", line 585, in lazy
    raise ValueError(
ValueError: allow_missing=True and no TTrees found in

    
```

**Comment by jpivarski** [comment]
Just leaving a note for fixing this in the future; it's somewhere in here:

https://github.com/scikit-hep/uproot4/blob/7e42e2f71d9fb20dbfb12d177403b3b0839d0cc2/uproot4/behaviors/TBranch.py#L2707-L2786
