### ISSUE TITLE
Reading empty branches with library="ak" produces EmptyArray despite known type

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/uproot4#126]
Reading empty branches (without data, but empty lists) with `library="ak"` creates `EmptyArray` contents for the awkward arrays

```pycon
>>> import skhep_testdata
>>> branch = uproot4.open(skhep_testdata.data_path("uproot-vectorVectorDouble.root"))["t/x"]
>>> branch.array(entry_stop=2, library="ak")
<Array [[], [[], []]] type='2 * var * var * unknown'>
```

In some cases this creates an error internally when uproot tries to access `.content`

```pycon
>>> branch.array(entry_stop=1, library="ak")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    branch.array(entry_stop=1, library="ak")
  File "/home/nikolai/python/uproot4/uproot4/behaviors/TBranch.py", line 2062, in array
    _ranges_or_baskets_to_arrays(
  File "/home/nikolai/python/uproot4/uproot4/behaviors/TBranch.py", line 3373, in _ranges_or_baskets_to_arrays
    uproot4.source.futures.delayed_raise(*obj)
  File "/home/nikolai/python/uproot4/uproot4/source/futures.py", line 46, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/home/nikolai/python/uproot4/uproot4/behaviors/TBranch.py", line 3344, in basket_to_array
    arrays[branch.cache_key] = interpretation.final_array(
  File "/home/nikolai/python/uproot4/uproot4/interpretation/objects.py", line 230, in final_array
    output = library.finalize(output, branch, self, entry_start, entry_stop)
  File "/home/nikolai/python/uproot4/uproot4/interpretation/library.py", line 496, in finalize
    return awkward1.Array(_awkward_json_to_array(awkward1, form, unlabeled))
  File "/home/nikolai/python/uproot4/uproot4/interpretation/library.py", line 360, in _awkward_json_to_array
    content = _awkward_json_to_array(awkward1, form["content"], array.content)
  File "/home/nikolai/python/uproot4/uproot4/interpretation/library.py", line 360, in _awkward_json_to_array
    content = _awkward_json_to_array(awkward1, form["content"], array.content)
AttributeError: 'awkward1._ext.EmptyArray' object has no attribute 'content'
```

or when record fields are being accessed (the following uses the example file `DAOD_PHYSLITE.art_split99.pool.root` from #124)

```pycon
>>> import uproot4
>>> branch = uproot4.open("issue-123a.root")["CollectionTree/TruthElectronsAuxDyn.childLinks"]
>>> branch.array()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    branch.array()
  File "/home/nikolai/python/uproot4/uproot4/behaviors/TBranch.py", line 2062, in array
    _ranges_or_baskets_to_arrays(
  File "/home/nikolai/python/uproot4/uproot4/behaviors/TBranch.py", line 3373, in _ranges_or_baskets_to_arrays
    uproot4.source.futures.delayed_raise(*obj)
  File "/home/nikolai/python/uproot4/uproot4/source/futures.py", line 46, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/home/nikolai/python/uproot4/uproot4/behaviors/TBranch.py", line 3344, in basket_to_array
    arrays[branch.cache_key] = interpretation.final_array(
  File "/home/nikolai/python/uproot4/uproot4/interpretation/objects.py", line 230, in final_array
    output = library.finalize(output, branch, self, entry_start, entry_stop)
  File "/home/nikolai/python/uproot4/uproot4/interpretation/library.py", line 496, in finalize
    return awkward1.Array(_awkward_json_to_array(awkward1, form, unlabeled))
  File "/home/nikolai/python/uproot4/uproot4/interpretation/library.py", line 360, in _awkward_json_to_array
    content = _awkward_json_to_array(awkward1, form["content"], array.content)
  File "/home/nikolai/python/uproot4/uproot4/interpretation/library.py", line 360, in _awkward_json_to_array
    content = _awkward_json_to_array(awkward1, form["content"], array.content)
  File "/home/nikolai/python/uproot4/uproot4/interpretation/library.py", line 335, in _awkward_json_to_array
    contents.append(_awkward_json_to_array(awkward1, subform, array[name]))
ValueError: cannot slice EmptyArray by field name

(https://github.com/scikit-hep/awkward-1.0/blob/0.3.1/src/libawkward/array/EmptyArray.cpp#L321)
```

I guess the array should have type information, since it is in principle known. It seems to get lost here:

https://github.com/scikit-hep/uproot4/blob/57fafcfd73c40aea21dd19a439c76c79fd370768/uproot4/interpretation/library.py#L493-L495

**Comment by jpivarski** [comment]
As a temporary solution (which will last for the rest of this year, likely), complex objects are passed through ak.from_iter, which makes EmptyArray when there are no instances of data from which to derive the type (like `[[], [], []]`). EmptyArrays have unknown type.

But the type is known by the calling function. Actually, it's in the Form. After getting an array via ak.from_iter, it gets post-processed here:

https://github.com/scikit-hep/uproot4/blob/57fafcfd73c40aea21dd19a439c76c79fd370768/uproot4/interpretation/library.py#L326-L370

And that post-processing should turn the EmptyArrays into relevant types, using information from the Form. I see that there aren't any cases catching EmptyArray, so this bug is due to missing code.

It could take me a few days to get to this.
