### ISSUE TITLE
Cannot read TProfile / TF1 using uproot4, works in uproot3

### ISSUE THREAD

**Issue by maxnoe** [scikit-hep/uproot4#181]
I can read the objects in the attached file using uproot 3, but uproot 4 raises the following exception.

[EbiasCorrection.root.zip](https://github.com/scikit-hep/uproot4/files/5499812/EbiasCorrection.root.zip)

```
import uproot4 as uproot  # works with uproot3


f = uproot.open('./EbiasCorrection.root')

for k in f.keys():
    print(f[k])

```

```
Traceback (most recent call last):
  File "read_ebias.py", line 7, in <module>
    print(f[k])
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/reading.py", line 1896, in __getitem__
    return self.key(where).get()
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/reading.py", line 2281, in get
    out = cls.read(chunk, cursor, context, self._file, selffile, parent)
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/model.py", line 1098, in read
    versioned_cls.read(
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/model.py", line 730, in read
    self.read_members(chunk, cursor, context, file)
  File "<dynamic>", line 7, in read_members
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/model.py", line 730, in read
    self.read_members(chunk, cursor, context, file)
  File "<dynamic>", line 7, in read_members
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/model.py", line 730, in read
    self.read_members(chunk, cursor, context, file)
  File "<dynamic>", line 19, in read_members
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/model.py", line 730, in read
    self.read_members(chunk, cursor, context, file)
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/models/TList.py", line 55, in read_members
    item = uproot4.deserialization.read_object_any(
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/deserialization.py", line 265, in read_object_any
    obj = cls.read(chunk, cursor, context, file, selffile, parent)
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/model.py", line 1098, in read
    versioned_cls.read(
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/model.py", line 730, in read
    self.read_members(chunk, cursor, context, file)
  File "<dynamic>", line 7, in read_members
  File "/home/maxnoe/.local/lib/python3.8/site-packages/uproot4/model.py", line 730, in read
    self.read_members(chunk, cursor, context, file)
  File "<dynamic>", line 10, in read_members
NameError: name 'fNoper' is not defined
```

**Comment by maxnoe** [comment]
ALso, I am a bit confused as what values I get from this.

This is the plot root draws for the `TProfile` ('meanetruevseest):
![tprofile](https://user-images.githubusercontent.com/5488440/98346506-586f7180-2016-11eb-830a-292d4e379104.png)


But when reading with uproot3 and plotting, I get this:
![uproot_tprofile](https://user-images.githubusercontent.com/5488440/98346793-c4ea7080-2016-11eb-98de-e2667e9c5988.png)

**Comment by jpivarski** [comment]
Thanks—that was a bug in code generation, in which `fNoper` wasn't quoted. That's what PR #186 fixes.

As for your questions, TF1 doesn't have any behaviors defined, so all you can do with it at the moment is

```python
>>> f["correctedE"].all_members
{'@fUniqueID': 0,
 '@fBits': 50332672,
 'fName': 'correctedE',
 'fTitle': 'pol5',
 'fNdim': 1,
 'fNpar': 6,
 'fNoper': 1,
 'fNconst': 0,
 'fNumber': 305,
 'fNval': 0,
 'fNstring': 0,
 'fExpr': <TString 'pol5' at 0x7f52e19c8cf0>,
 'fOper': array([1090519541], dtype=int32),
 'fConst': array([], dtype=float64),
 'fParams': array([ 7.96960054e-03,  9.95640665e-01,  8.74907519e-04,  3.23497673e-03,
                   -3.36583446e-03,  1.35120768e-03]),
 'fNames': <TString '' at 0x7f52e19290b0>,
 'fFunctions': <TObjArray of 0 items at 0x7f52e191a4f0>,
 'fLinearParts': <TObjArray of 0 items at 0x7f52e191a880>,
 'fLineColor': 2,
 'fLineStyle': 1,
 'fLineWidth': 2,
 'fFillColor': 19,
 'fFillStyle': 0,
 'fMarkerColor': 1,
 'fMarkerStyle': 1,
 'fMarkerSize': 1.0,
 'fXmin': -1.899999976158142,
 'fXmax': 2.2999999523162846,
 'fNpx': 100,
 'fType': 0,
 'fNpfits': 418,
 'fNDF': 412,
 'fNsave': 103,
 'fChisquare': 0.05494463858791303,
 'fParErrors': array([0.09455276, 0.16740379, 0.15668286, 0.14833426, 0.04744522,
                      0.0319801 ]),
 'fParMin': array([0., 0., 0., 0., 0., 0.]),
 'fParMax': array([0., 0., 0., 0., 0., 0.]),
 'fSave': array([-1.98009905e+00, -1.92969130e+00, -1.87989590e+00, -1.83068014e+00,
                 -1.78201250e+00, -1.73386258e+00, -1.68620112e+00, -1.63899996e+00,
                 -1.59223201e+00, -1.54587127e+00, -1.49989275e+00, -1.45427250e+00,
                 -1.40898757e+00, -1.36401596e+00, -1.31933666e+00, -1.27492957e+00,
                 -1.23077552e+00, -1.18685621e+00, -1.14315424e+00, -1.09965304e+00,
                 -1.05633687e+00, -1.01319080e+00, -9.70200691e-01, -9.27353164e-01,
                 -8.84635586e-01, -8.42036043e-01, -7.99543325e-01, -7.57146903e-01,
                 -7.14836906e-01, -6.72604099e-01, -6.30439868e-01, -5.88336191e-01,
                 -5.46285621e-01, -5.04281264e-01, -4.62316759e-01, -4.20386254e-01,
                 -3.78484389e-01, -3.36606269e-01, -2.94747449e-01, -2.52903909e-01,
                 -2.11072032e-01, -1.69248587e-01, -1.27430706e-01, -8.56158578e-02,
                 -4.38018359e-02, -1.98673020e-03,  3.98310912e-02,  8.16530039e-02,
                  1.23480148e-01,  1.65313451e-01,  2.07153645e-01,  2.49001292e-01,
                  2.90856804e-01,  3.32720463e-01,  3.74592443e-01,  4.16472832e-01,
                  4.58361649e-01,  5.00258874e-01,  5.42164459e-01,  5.84078356e-01,
                  6.26000535e-01,  6.67931008e-01,  7.09869847e-01,  7.51817206e-01,
                  7.93773346e-01,  8.35738649e-01,  8.77713645e-01,  9.19699033e-01,
                  9.61695698e-01,  1.00370474e+00,  1.04572747e+00,  1.08776549e+00,
                  1.12982064e+00,  1.17189507e+00,  1.21399124e+00,  1.25611195e+00,
                  1.29826036e+00,  1.34044000e+00,  1.38265482e+00,  1.42490917e+00,
                  1.46720785e+00,  1.50955614e+00,  1.55195978e+00,  1.59442503e+00,
                  1.63695868e+00,  1.67956806e+00,  1.72226107e+00,  1.76504621e+00,
                  1.80793260e+00,  1.85092996e+00,  1.89404871e+00,  1.93729990e+00,
                  1.98069532e+00,  2.02424744e+00,  2.06796950e+00,  2.11187549e+00,
                  2.15598017e+00,  2.20029912e+00,  2.24484874e+00,  2.28964627e+00,
                  2.33470981e+00, -1.89999998e+00,  2.29999995e+00]),
 'fMaximum': -1111.0,
 'fMinimum': -1111.0}
```

If you have a suggestion for how this should be plotted or something, let me know. We should try to give it a similar interface to histograms, which is in flux: #167 and scikit-hep/boost-histogram#423.

One of the mistakes in Uproot 3 was to reproduce the ROOT C++ class hierarchy in the Python class hierarchy, which have the TProfile some odd behavior (because it descended from TH1). That has been separated in Uproot 4 and TProfiles have `to_boost` and `to_hist` methods for boost-histogram and hist, respectively. Unfortunately, it doesn't work:

```
AttributeError: 'WeightedMeanView' object has no attribute 'sum_of_weighted_deltas_squared'
```

I made some wrong assumption about the structure of a boost-histogram (#167 again). In the meantime, `values_errors` gives the profile values and their errors as two NumPy arrays.

**Comment by maxnoe** [comment]
@jpivarski thanks!

Any idea about the `TProfile` business?

**Comment by jpivarski** [comment]
This is what I meant:

> One of the mistakes in Uproot 3 was to reproduce the ROOT C++ class hierarchy in the Python class hierarchy, which have the TProfile some odd behavior (because it descended from TH1).

I don't think the output of TProfile was ever addressed in Uproot 3. But I do know that I made `TProfile.values_errors` exactly identical to ROOT's output in Uproot 4.

**Comment by maxnoe** [comment]
Ok, thanks again, will try
