### ISSUE TITLE
DeserializationError while reading file uproot3 can read

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/uproot4#188]
As part of https://github.com/scikit-hep/pyhf/pull/1002/ I've been seeing a `uproot4.deserialization.DeserializationError` and while looking at it more closely today I realized it seemed strange so I thought I'd report it.

## Minimal Failing Example

`uproot4-issue.py`:

```python
import uproot4 as uproot
import uproot as uproot3


def main():
    # curl -sL https://github.com/scikit-hep/pyhf/raw/master/validation/xmlimport_input3/data/ShapeSys.root -o ShapeSys.root
    uproot3_file = uproot3.open("ShapeSys.root")

    uproot3_signal_hist = uproot3_file["signal"]
    print(f"uproot 3 signal hist: {uproot3_signal_hist.numpy()}")

    # This will fail
    uproot4_file = uproot.open("ShapeSys.root")
    print(f"uproot 4 file keys: {uproot4_file.keys()}")
    uproot4_signal_hist = uproot4_file["signal"]


if __name__ == '__main__':
    main()
```

In a new Python 3 virtual environment:

```
(uproot4-issue) $ cat requirements.txt 
uproot~=3.13.0
uproot4==0.1.2
(uproot4-issue) $ pip install -q -r requirements.txt
(uproot4-issue) $ curl -sL https://github.com/scikit-hep/pyhf/raw/master/validation/xmlimport_input3/data/ShapeSys.root -o ShapeSys.root
(uproot4-issue) $ python uproot4-issue.py
```
gives
```pytb
uproot 3 signal hist: (array([20., 10.], dtype=float32), array([0., 1., 2.]))
uproot 4 file keys: ['signal;1', 'background1;2', 'background1;1', 'bkg1ShapeError;1', 'background2;2', 'background2;1', 'bkg2ShapeError;1', 'data;1']
Traceback (most recent call last):
  File "uproot4-issue.py", line 19, in <module>
    main()
  File "uproot4-issue.py", line 15, in main
    uproot4_signal_hist = uproot4_file["signal"]
  File "/home/feickert/.venvs/uproot4-issue/lib/python3.7/site-packages/uproot4/reading.py", line 1979, in __getitem__
    return self.key(where).get()
  File "/home/feickert/.venvs/uproot4-issue/lib/python3.7/site-packages/uproot4/reading.py", line 2364, in get
    out = cls.read(chunk, cursor, context, self._file, selffile, parent)
  File "/home/feickert/.venvs/uproot4-issue/lib/python3.7/site-packages/uproot4/model.py", line 1143, in read
    chunk, cursor, context, file, selffile, parent, concrete=concrete
  File "/home/feickert/.venvs/uproot4-issue/lib/python3.7/site-packages/uproot4/model.py", line 773, in read
    self.read_members(chunk, cursor, context, file)
  File "<dynamic>", line 7, in read_members
  File "/home/feickert/.venvs/uproot4-issue/lib/python3.7/site-packages/uproot4/model.py", line 779, in read
    self.check_numbytes(chunk, cursor, context)
  File "/home/feickert/.venvs/uproot4-issue/lib/python3.7/site-packages/uproot4/model.py", line 861, in check_numbytes
    getattr(self._file, "file_path"),
  File "/home/feickert/.venvs/uproot4-issue/lib/python3.7/site-packages/uproot4/deserialization.py", line 177, in numbytes_check
    file_path,
uproot4.deserialization.DeserializationError: while reading

    TH1F version 2 as uproot4.dynamic.Model_TH1F_v2 (548 bytes)
        TH1 version 7 as uproot4.dynamic.Model_TH1_v8 (522 bytes)
            (base): <TNamed 'signal' title='signal' at 0x7fed7c232550>
            (base): <TAttLine (version 2) at 0x7fed7c13e6d0>
            (base): <TAttFill (version 2) at 0x7fed7c13e750>
            (base): <TAttMarker (version 2) at 0x7fed7c13e7d0>
            fNcells: 4
            fXaxis: <TAxis (version 10) at 0x7fed7c13e890>
            fYaxis: <TAxis (version 10) at 0x7fed7c13fc90>
            fZaxis: <TAxis (version 10) at 0x7fed7c13f310>
            fBarOffset: 0
            fBarWidth: 1000
            fEntries: 2.0
            fTsumw: 0.0
            fTsumw2: 0.0
            fTsumwx: 0.0
            fTsumwx2: 0.0
            fMaximum: -1111.0
            fMinimum: -1111.0
            fNormFactor: 0.0
            fContour: <TArrayD [] at 0x7fed7c13f710>
            fSumw2: <TArrayD [] at 0x7fed7c13e790>
            fOption: <TString '' at 0x7fed7c210150>
            fFunctions: <TList of 0 items at 0x7fed7c13fe10>
            fBufferSize: 0
            fBuffer: array([], dtype=float64)
            fBinStatErrOpt: 0
            fStatOverflows: 4
Base classes for TH1: (TNamed), (TAttLine), (TAttFill), (TAttMarker)
Members for TH1: (fNcells), (fXaxis), (fYaxis), (fZaxis), (fBarOffset), (fBarWidth), (fEntries), (fTsumw), (fTsumw2), (fTsumwx), (fTsumwx2), (fMaximum), (fMinimum), (fNormFactor), (fContour), (fSumw2), (fOption), (fFunctions), (fBufferSize), (fBuffer), (fBinStatErrOpt), (fStatOverflows)

expected 522 bytes but cursor moved by 526 bytes (through TH1)
in file ShapeSys.root
in object /signal;1
```

cc @lukasheinrich @kratsg

**Comment by jpivarski** [comment]
It fails because of something in the error message:

```
        TH1 version 7 as uproot4.dynamic.Model_TH1_v8 (522 bytes)
```

It's trying to load a TH1 version 7 using a class named `Model_TH1_v8`. The difference between version 7 and version 8 is that the latter has one more 4 byte member, and that's why

```
expected 522 bytes but cursor moved by 526 bytes (through TH1)
```

Why's it using a version 8 class when it's a version 7 instance? _Because the streamer for TH1F told it to._

```python
>>> f = uproot4.open("issue-188.root")
>>> f.file.streamer_named("TH1F").show()
TH1F (v2): TH1 (v8), TArrayF (v1)
```

That's wrong—we certainly couldn't call this file "not broken," but it works in Uproot 3 and presumably ROOT, so there should be a work-around. [PR #199](https://github.com/scikit-hep/uproot4/pull/199/files#diff-b9429ed79bcc66f23bf0f1637ee53386fe73c32932e7fcf0201f260f2b14263e) adds a fallback to rewind the deserialization and try again when it starts with the wrong class. That's how Uproot 3 worked throughout, because I hadn't thought through class versioning before writing it. Uproot 4 was meant to detangle that mess by dealing with class versions up-front, but sometimes the information given up-front is wrong.

**Comment by matthewfeickert** [comment]
Thanks very much @jpivarski. :+1:
