### ISSUE TITLE
Cannot read tree from file, though working in uproot3

### ISSUE THREAD

**Issue by DavidLeibold** [scikit-hep/uproot4#259]
Hello,

a colleague of mine ran into [this file](https://github.com/scikit-hep/uproot4/files/5945153/onepinhole.root.zip) whose tree `Hits` can be opened by uproot3, but not by uproot4.  I have to note in advance that the trees in this file are all empty.

The minimal not-working example is as follows:

        import uproot
        test = uproot.open("onepinhole.root")
        TestDf = test['Hits'].arrays("*")

This will throw the following error message:

        Traceback (most recent call last):
        
          File "/Users/david/Library/Python-Anaconda/anaconda3/envs/phdpython/lib/python3.7/site-packages/uproot/language/python.py", line 22, in _expression_to_node
            node = ast.parse(expression)
        
          File "/Users/david/Library/Python-Anaconda/anaconda3/envs/phdpython/lib/python3.7/ast.py", line 35, in parse
            return compile(source, filename, mode, PyCF_ONLY_AST)
        
          File "<unknown>", line 1
            *
             ^
        SyntaxError: invalid syntax
        
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
        
          File "/Users/david/Library/Python-Anaconda/anaconda3/envs/phdpython/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
            exec(code_obj, self.user_global_ns, self.user_ns)
        
          File "<ipython-input-4-a148e06a1500>", line 1, in <module>
            HitsDf = test['Hits'].arrays("*")
        
          File "/Users/david/Library/Python-Anaconda/anaconda3/envs/phdpython/lib/python3.7/site-packages/uproot/behaviors/TBranch.py", line 1098, in arrays
            get_from_cache,
        
          File "/Users/david/Library/Python-Anaconda/anaconda3/envs/phdpython/lib/python3.7/site-packages/uproot/behaviors/TBranch.py", line 3238, in _regularize_expressions
            None,
        
          File "/Users/david/Library/Python-Anaconda/anaconda3/envs/phdpython/lib/python3.7/site-packages/uproot/behaviors/TBranch.py", line 3131, in _regularize_expression
            hasbranches.object_path,
        
          File "/Users/david/Library/Python-Anaconda/anaconda3/envs/phdpython/lib/python3.7/site-packages/uproot/language/python.py", line 374, in free_symbols
            node = _expression_to_node(expression, file_path, object_path)
        
          File "/Users/david/Library/Python-Anaconda/anaconda3/envs/phdpython/lib/python3.7/site-packages/uproot/language/python.py", line 26, in _expression_to_node
            err.args[1],
        
          File "<unknown>", line 1
            *
             ^
        SyntaxError: invalid syntax
        in file onepinhole.root
        in object /Hits;1

-------------

The environment with which the example fails is as follows:

      
        Lawkward                  1.0.2                        
        lz4                       3.1.3    
        numpy                     1.16.4                         
        python                    3.7.3                 
        uproot                    4.0.2                        
        xxhash                    2.0.0                        

The environment with with the example does not fail is as follows:

        awkward                   0.14.0                   
        cachetools                4.2.1                    
        lz4                       3.1.3             
        numpy                     1.16.4       
        python                    3.7.3       
        uproot3                   3.14.3                   
        uproot3-methods           0.10.0                   
        xxhash                    2.0.0                    

Unfortunately, I don't understand the error traceback to fix this error myself. If you need further information, please let me know!

Best,
David

**Comment by tamasgal** [comment]
Hi David,

the syntax has changed in `uproot` v4 to access multiple arrays. Try this:

```python
import uproot
test = uproot.open("onepinhole.root")
TestDf = test['Hits'].arrays()
```

This will give you an instance of `awkward.Array`:

```
>>> TestDf
<Array [] type='0 * {"PDGEncoding": int32, "trackID": int32, "parentID": int32, ...'>

>>> type(TestDf)
awkward.highlevel.Array

>>> TestDf["PDGEncoding"]
<Array [] type='0 * int32'>
```

**Comment by DavidLeibold** [comment]
I am really sorry, I should have read the documentation on the transition. It does now work as expected. Thanks a lot @tamasgal for your quick response!

**Comment by tamasgal** [comment]
No worries and don't hesitate to ask, we all are busy and overlook things here and there 😉

**Comment by DavidLeibold** [comment]
Thanks! 😊

**Comment by jpivarski** [comment]
Thanks @tamasgal!
