### ISSUE TITLE
uproot4.iterate on Empty TTree Object

### ISSUE THREAD

**Issue by ElegantCosmos** [scikit-hep/uproot4#335]
I am using uproot version 4.0.7 iterate to read through several TTree objects.
When a TTree object happens to be empty (i.e. with no entries), I get an error.
I think the correct behavior should be that no error is encountered and the empty Tree is ignored.
I have attached a sample ROOT file with an empty Tree inside:
[empty_tree.txt](https://github.com/scikit-hep/uproot4/files/6327025/empty_tree.txt)
Please rename `empty_tree.txt` to `empty_tree.root`.
The code that fails to read it is:

```python
import uproot
print("uproot.__version__", uproot.__version__)

for dataframe in uproot.iterate("empty_tree.root:empty_tree", ['var'], library='pd'): 
	print("dataframe\n", dataframe)
```

The error message I see is:

```
uproot.__version__ 4.0.7
Traceback (most recent call last):
  File "iterate_through_empty_tree.py", line 5, in <module>
    for dataframe in uproot.iterate("empty_tree.root:empty_tree", ['var'], library='pd'):
  File "/home/name/.opt/python/miniconda3.8/envs/omega-analysis/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 205, in iterate
    for item in hasbranches.iterate(
  File "/home/name/.opt/python/miniconda3.8/envs/omega-analysis/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 1316, in iterate
    entry_step = _regularize_step_size(
  File "/home/name/.opt/python/miniconda3.8/envs/omega-analysis/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 3540, in _regularize_step_size
    return _hasbranches_num_entries_for(
  File "/home/name/.opt/python/miniconda3.8/envs/omega-analysis/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 3523, in _hasbranches_num_entries_for
    num_entries = int(round(target_num_bytes * total_entries / total_bytes))
ZeroDivisionError: float division by zero
```

**Comment by jpivarski** [comment]
Thanks!

(Sheesh—division by zero!)
