### ISSUE TITLE
uproot4.lazy fails to read TBranch of type std::vector<TLorentzVector>

### ISSUE THREAD

**Issue by davehadley** [scikit-hep/uproot4#402]
`uproot4.lazy` fails to read branches of type `std::vector<TLorentzVector>` that `uproot4.open` and `uproot4.concatenate` read successfully.

I am using uproot version `4.0.11`, ROOT `6.20/00`.

The following script reproduces the problem:

```python
import ROOT
import uproot4
from importlib.metadata import version

# some C++ code that generates an example file
ROOT.gInterpreter.GenerateDictionary("std::vector<TLorentzVector>", "vector;TLorentzVector.h")
ROOT.gInterpreter.ProcessLine("""
#include <vector>
#include "TLorentzVector.h"

void write_file() {
    TFile tfile("example.root", "RECREATE");
    TTree tree("tree", "tree");
    std::vector<TLorentzVector> fourMomentum;
    tree.Branch("fourMomentum", &fourMomentum);
    fourMomentum.push_back({1.0, 2.0, 3.0, 4.0});
    tree.Fill();
    tree.AutoSave();
    return;
}
""")

if __name__ == "__main__":
    ROOT.write_file()

    # check versions
    print(version("uproot")) # prints: 4.0.11
    print(ROOT.gROOT.GetVersion()) # prints: 6.20/00

    # read with uproot
    tree = uproot4.open("example.root:tree")
    print(tree.arrays(library="ak").fourMomentum)
    # prints: [[{fP: {fX: 1, fY: 2, fZ: 3}, fE: 4}]]

    # read with uproot concatenate
    tree = uproot4.concatenate(["example.root:tree"], library="ak")
    print(tree.fourMomentum) 
    # prints: [[{fP: {fX: 1, fY: 2, fZ: 3}, fE: 4}]]

    # read lazily with uproot
    tree = uproot4.lazy(["example.root:tree"], library="ak")
    print(tree.fourMomentum) # raises ValueError
```

This produces the error message:

```
/home/epp/phskaj/work/t2k/ncfgd7/ncfgd/env/ncfgd/lib/python3.8/site-packages/uproot/reading.py:186: FutureWarning: XRootD 4.11.3 is not fully supported; either upgrade to 5.2.0+ or set

    open.defaults["xrootd_handler"] = uproot.MultithreadedXRootDSource

  warnings.warn(message, FutureWarning)
TTree::Bronch:0: RuntimeWarning: Using split mode on a class: TLorentzVector with a custom Streamer
4.0.11
6.20/00
[[{fP: {fX: 1, fY: 2, fZ: 3}, fE: 4}]]
[[{fP: {fX: 1, fY: 2, fZ: 3}, fE: 4}]]
Traceback (most recent call last):
  File "possible_bug_in_uproot.py", line 42, in <module>
    print(tree.fourMomentum) # raises ValueError
  File "/home/epp/phskaj/work/t2k/ncfgd7/ncfgd/env/ncfgd/lib/python3.8/site-packages/awkward/highlevel.py", line 1278, in __str__
    return self._str()
  File "/home/epp/phskaj/work/t2k/ncfgd7/ncfgd/env/ncfgd/lib/python3.8/site-packages/awkward/highlevel.py", line 1298, in _str
    return ak._util.minimally_touching_string(
  File "/home/epp/phskaj/work/t2k/ncfgd7/ncfgd/env/ncfgd/lib/python3.8/site-packages/awkward/_util.py", line 1567, in minimally_touching_string
    rgt = next(rightgen)
  File "/home/epp/phskaj/work/t2k/ncfgd7/ncfgd/env/ncfgd/lib/python3.8/site-packages/awkward/_util.py", line 1553, in forever
    for token in iterable:
  File "/home/epp/phskaj/work/t2k/ncfgd7/ncfgd/env/ncfgd/lib/python3.8/site-packages/awkward/_util.py", line 1509, in backward
    for token in backward(x[i], sp):
  File "/home/epp/phskaj/work/t2k/ncfgd7/ncfgd/env/ncfgd/lib/python3.8/site-packages/awkward/partition.py", line 231, in __getitem__
    return PartitionedArray.from_ext(self._ext.getitem_at(where))
ValueError: generated array does not conform to expected form:

{
    "class": "ListOffsetArray64",
    "offsets": "i64",
    "content": {
        "class": "RecordArray",
        "contents": {
            "@fBits": "uint32",
            "@fUniqueID": "uint32",
            "@instance_version": "uint16",
            "@num_bytes": "uint32",
            "@pidf": "uint16",
            "fE": "float64",
            "fP": {
                "class": "RecordArray",
                "contents": {
                    "@fBits": "uint32",
                    "@fUniqueID": "uint32",
                    "@instance_version": "uint16",
                    "@num_bytes": "uint32",
                    "@pidf": "uint16",
                    "fX": "float64",
                    "fY": "float64",
                    "fZ": "float64"
                },
                "parameters": {
                    "__record__": "TVector3"
                }
            }
        },
        "parameters": {
            "__record__": "TLorentzVector"
        }
    }
}

but generated:

{
    "class": "ListOffsetArray64",
    "offsets": "i64",
    "content": {
[example.zip](https://github.com/scikit-hep/uproot4/files/6907761/example.zip)

        "class": "RecordArray",
        "contents": {
            "fP": {
                "class": "RecordArray",
                "contents": {
                    "fX": "float64",
                    "fY": "float64",
                    "fZ": "float64"
                },
                "parameters": {
                    "__record__": "TVector3"
                }
            },
            "fE": "float64"
        },
        "parameters": {
            "__record__": "TLorentzVector"
        }
    }
}

(https://github.com/scikit-hep/awkward-1.0/blob/1.2.3/src/libawkward/virtual/ArrayGenerator.cpp#L46)```

```

I have also attached `example.root` to this issue. 

[example.zip](https://github.com/scikit-hep/uproot4/files/6908136/example.zip)

**Comment by davehadley** [comment]
My `awkward` version in the above test was: `1.2.3`.
I have updated to latest (`1.4.0`) and see the same error.

**Comment by jpivarski** [comment]
I'll take a look at example.zip, although it's strange that it fails while this one succeeds (also a `std::vector<TLorentzVector>`):

```python
>>> import uproot, skhep_testdata
>>> skhep_testdata.data_path("uproot-HZZ-objects.root")
'/home/jpivarski/.local/skhepdata/uproot-HZZ-objects.root'
>>> f = uproot.open(skhep_testdata.data_path("uproot-HZZ-objects.root"))
>>> t = f["events"]
>>> t.show()
name                 | typename                 | interpretation                
---------------------+--------------------------+-------------------------------
jetp4                | std::vector<TLorentzV... | AsJagged(AsStridedObjects(M...
jetbtag              | std::vector<float>       | AsJagged(AsDtype('>f4'), he...
jetid                | std::vector<bool>        | AsJagged(AsDtype('bool'), h...
muonp4               | std::vector<TLorentzV... | AsJagged(AsStridedObjects(M...
muonq                | std::vector<int32_t>     | AsJagged(AsDtype('>i4'), he...
muoniso              | std::vector<float>       | AsJagged(AsDtype('>f4'), he...
electronp4           | std::vector<TLorentzV... | AsJagged(AsStridedObjects(M...
electronq            | std::vector<int32_t>     | AsJagged(AsDtype('>i4'), he...
electroniso          | std::vector<float>       | AsJagged(AsDtype('>f4'), he...
photonp4             | std::vector<TLorentzV... | AsJagged(AsStridedObjects(M...
photoniso            | std::vector<float>       | AsJagged(AsDtype('>f4'), he...
MET                  | TVector2                 | AsStridedObjects(Model_TVec...
MC_bquarkhadronic    | TVector3                 | AsStridedObjects(Model_TVec...
MC_bquarkleptonic    | TVector3                 | AsStridedObjects(Model_TVec...
MC_wdecayb           | TVector3                 | AsStridedObjects(Model_TVec...
MC_wdecaybbar        | TVector3                 | AsStridedObjects(Model_TVec...
MC_lepton            | TVector3                 | AsStridedObjects(Model_TVec...
MC_leptonpdgid       | int32_t                  | AsDtype('>i4')
MC_neutrino          | TVector3                 | AsStridedObjects(Model_TVec...
num_primaryvertex    | int32_t                  | AsDtype('>i4')
trigger_isomu24      | bool                     | AsDtype('bool')
eventweight          | float                    | AsDtype('>f4')
>>> t["jetp4"].array()
<Array [[], [{fP: {, ... fE: 33.9}], []] type='2421 * var * TLorentzVector["fP":...'>
```

**Comment by jpivarski** [comment]
Nevermind: I missed the fact that you saw this behavior in `uproot.lazy` and not in eager array-reading. Got it.

**Comment by davehadley** [comment]
Yes that's right. It seems to just be `lazy` causing errors. Everything else seems to work as expected.

I have just tried the example file that you are looking at and I see the same error if I do:

```shell
wget "https://github.com/scikit-hep/scikit-hep-testdata/blob/main/src/skhep_testdata/data/uproot-HZZ-objects.root?raw=true" -O hzz.root
python -c "import uproot4; print(uproot4.lazy('hzz.root:events'));"
```

So it seems to be reproducible with different input files. Of course, that doesn't eliminate the possibility that it might just be a problem on my system / installation.

**Comment by jpivarski** [comment]
It's not an installation issue; PR #403 should fix it.

The fields that start with "@" symbols are TObject members that are unlikely to be meaningful in an analysis, but they're necessary for deserialization. The default Interpretations drop these fields (I put the "@" sign there as an indicator to later code of what to drop). In lazy arrays, the reading is deferred for later, but there are a lot of operations that can proceed if they only know the type of the data, so lazy arrays have a Form object (detailed type) to answer those questions without invoking a disk-read. However, when the array is finally read, if its actual type differs from what it's been telling everybody, that needs to be an error. In this case, the "@" fields were not removed from the Form as they are removed from the data that gets read—this was inconsistent, and Awkward Array (which knows nothing about all this) raised an error because of the inconsistency. That's what its error was saying: the first Form had a bunch of fields with "@" signs in them; the second didn't. The fix was to make the Forms consistent with the data by removing fields that start with "@" signs.

That's the long explanation.
