### ISSUE TITLE
Wrong data type for TObject/fBits

### ISSUE THREAD

**Issue by tfruth** [scikit-hep/uproot4#569]
Dear uproot team,

I am seeing the following issue with uproot 4.1.8, 4.1.9 and 4.2.0 (I have not tried other versions). The TObject/fBits branch data type is interpreted as 8 bit instead of 32 bit. This leads to issues when trying to read the branch entries as I suspect the binary gets split in the wrong way and the number of branch entries does not match anymore. It leads to an error. This is causing some problems when for example using uproot to compare to root files.

Here an example:
```python
>>> import uproot
>>> events = uproot.open("file.root:MCTruthTree")
>>> events["MCTruthEvent/TObject/fBits"].array(library="pd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fruth/miniforge3/lib/python3.9/site-packages/uproot/behaviors/TBranch.py", line 2095, in array
    _ranges_or_baskets_to_arrays(
  File "/Users/fruth/miniforge3/lib/python3.9/site-packages/uproot/behaviors/TBranch.py", line 3510, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/Users/fruth/miniforge3/lib/python3.9/site-packages/uproot/source/futures.py", line 46, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/Users/fruth/miniforge3/lib/python3.9/site-packages/uproot/behaviors/TBranch.py", line 3464, in basket_to_array
    raise ValueError(
ValueError: basket 0 in tree/branch /MCTruthTree;1:MCTruthEvent/TObject/fBits has the wrong number of entries (expected 50, obtained 200) when interpreted as AsDtype('uint8')

**Comment by tfruth** [comment]
This is an example file to reproduce the error:
[MockSource_mctruth.txt](https://github.com/scikit-hep/uproot4/files/8187500/MockSource_mctruth.txt)

**Comment by jpivarski** [comment]
I'm digging into this, but the first thing I can say is, try

```python
>>> events["MCTruthEvent/TObject/fBits"].array(uproot.AsDtype(">i4"))
<Array [50331648] type='1 * int32'>
```

Now I'm looking into why `fBits` is coming up as 8-bit. The streamer says otherwise:

```python
>>> events.file.streamer_named("TObject").show()
TObject (v1)
    fUniqueID: unsigned int (TStreamerBasicType)
    fBits: unsigned int (TStreamerBasicType)
```

but there must be a reason, likely having to do with making other files readable. I'll let you know what I find.

**Comment by jpivarski** [comment]
It's because it's being explicitly set to be 8-bit:

https://github.com/scikit-hep/uproot4/blob/916085ae24c382404254756c86afe760acdece56/src/uproot/interpretation/identify.py#L381-L387

because that was the case in a file made by Delphes, reported in #438 and "fixed" in PR #454. As can be seen in the PR write-up, there wasn't anything special in the file saying, "I'm a weird file with 8-byte fBits!" If I fix it for this, I'll break it for that. I have to think about what to do about this.
