### ISSUE TITLE
Cursor.skip_over can only be used on an object with non-null `num_bytes`

### ISSUE THREAD

**Issue by raymondEhlers** [scikit-hep/uproot4#64]
Using uproot4 v'0.0.16', when trying to read a tree that was copied from another file (may be coincidental - just including all details), I receive the following traceback:

```
>>> import uproot4 as uproot
>>> f = uproot.open("AnalysisResults.root")
>>> f.keys()
['AliAnalysisTask;3']
>>> f["AliAnalysisTask"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/reading.py", line 1371, in __getitem__
    return self.key(where).get()
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/reading.py", line 870, in get
    out = cls.read(chunk, cursor, context, self._file, self)
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/model.py", line 478, in read
    versioned_cls.read(chunk, cursor, context, file, parent, concrete=concrete),
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/model.py", line 123, in read
    self.read_members(chunk, cursor, context)
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/models/TTree.py", line 665, in read_members
    chunk, cursor, context, self._file, self._concrete
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/model.py", line 123, in read
    self.read_members(chunk, cursor, context)
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/models/TObjArray.py", line 42, in read_members
    chunk, cursor, context, self._file, self._parent
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/deserialization.py", line 280, in read_object_any
    obj = cls.read(chunk, cursor, context, file, parent)
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/model.py", line 478, in read
    versioned_cls.read(chunk, cursor, context, file, parent, concrete=concrete),
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/model.py", line 123, in read
    self.read_members(chunk, cursor, context)
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/models/TBranch.py", line 626, in read_members
    concrete=self._concrete,
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/model.py", line 123, in read
    self.read_members(chunk, cursor, context)
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/models/TBranch.py", line 296, in read_members
    cursor.skip_over(chunk, context)
  File "/alf/data/rehlers/substructure/.venv/lib/python3.7/site-packages/uproot4/source/cursor.py", line 152, in skip_over
    "Cursor.skip_over can only be used on an object with non-null "
TypeError: Cursor.skip_over can only be used on an object with non-null `num_bytes`
```

I can read the tree just fine in root v6.20/02 (+ some alice patches). I can send the file, but need to keep it private, so I can't post it here. Any help or suggestions are appreciated!

**Comment by jpivarski** [comment]
Depending on what it is, you might not want to skip over it, regardless of the fact that it doesn't provide a `num_bytes` to be able to do that. There is some type that doesn't have a TStreamer and Uproot failed to even give up on it, labeling it "Unknown," because it didn't know how big the instance is and where it can start reading next.

Note to self: this error message should at least print out the name of the class—that would be better diagnostic information.

About your file, you could send it to my GMail address, which is jpivarski.

**Comment by raymondEhlers** [comment]
Thanks for your quick response!

Okay, I see, thanks - something must have been corrupted in the copying the tree from the other file (others succeeded, hence my surprise with this noe). For completeness I'll send you the file in case it helps with creating the error message, but since I can just regenerate it, I'll just do that

**Comment by raymondEhlers** [comment]
My conclusion above stands, but one other note: curiously, uproot3 can read it successfully (at least the number of entries, which is all I was trying to do at the moment)

**Comment by jpivarski** [comment]
I wouldn't call this "corrupted," but ROOT used a different option for writing it (and perhaps we don't know why it chose that option). It comes in trying to skip over embedded baskets (what I call TBaskets that are serialized as part of a TBranch, rather than being located elsewhere in the file with a TKey), which for this one file lacked the number of bytes (didn't have the `kByteCountMask` bit set). In PR #65, I've added a fallback to actually reading those embedded baskets in this case—at worst, it's extra reading, but in this case it's an empty TObjArray.

Just from reading the code, I don't see why Uproot 3 succeeded on this file. (But I haven't gone to the trouble of running a test and figuring out why. There must be a reason; I just don't see it at a glance.)

If you need a workaround faster than I can get this PR merged (Windows is failing to get conda, and therefore the tests are failing), the `uproot4.open` parameter `minimal_ttree_metadata=False` switches off this attempt to skip embedded baskets and makes your file readable without any code updates.

**Comment by raymondEhlers** [comment]
Ah, okay, now I think I understand - I read a bit too quickly before :-) Thanks for the explanation, the workaround, and the fix!
